### ISSUE TITLE
ToDo's Back-End

### ISSUE THREAD

**Issue by nikolockenvitz** [wwi17seb/dhbw-project-backend#88]
- [x] rated is an attribute of module and not of an academicRecord
- [x] valid_from year for majorSubjects
- [x] pdf upload: maybe cv should not be sent by default (because the file could be large), maybe it should be stored somewhere else and not in database, ...
- [x] transfer "ownership" of everyting (courses, lecturers, presentation?) to another DoS
- [x] allow DoS to edit/delete lecturers created by others when flag `allow_manipulation` is set
- [x] <s>unique constraints, e.g. for names of majorSubject and fieldOfStudy?</s>
